#!/bin/bash

export GRADLE_USER_HOME=$OPENSHIFT_DATA_DIR/gradle
export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export PATH=$JAVA_HOME/bin:$PATH

cd $OPENSHIFT_REPO_DIR
chmod +x gradlew
./gradlew dependencies -Penv=openshiftDev 2> $OPENSHIFT_LOG_DIR/build.log
./gradlew stage  -Penv=openshiftDev 2> $OPENSHIFT_LOG_DIR/stage.log