#!/bin/bash

cd $OPENSHIFT_REPO_DIR

export GRADLE_USER_HOME=$OPENSHIFT_DATA_DIR/gradle
export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export PATH=$JAVA_HOME/bin:$PATH

echo "Executing DB migrations..."
./gradlew updateDb -Penv=openshiftDev >> $OPENSHIFT_LOG_DIR/migrations.log 2>&1