#!/bin/bash

cd $OPENSHIFT_REPO_DIR
export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export PATH=$JAVA_HOME/bin:$PATH
java -Xms384m -Xmx412m -jar graffitab.jar --server.port=$OPENSHIFT_DIY_PORT --server.address=$OPENSHIFT_DIY_IP \
--db.username=$OPENSHIFT_MYSQL_DB_USERNAME --db.password=$OPENSHIFT_MYSQL_DB_PASSWORD &