FORMAT: 1A
HOST: http://dev.graffitab.com/api/

# GraffiTab REST API

Use our API to quickly integrate GraffiTab's services in your application.

# Group Authentication

## Basic authentication [/28]

### Get basic authentication token [GET /auth/token/basic?username={username}&password={password}]

+ Parameters
    + username (string) - The username of the user to authenticate.
    + password (string) - The password of the user to authenticate.
    
+ Response 200 (application/json)

        {
            "token": "[basic_auth_token]"
        }

# Group Users

## Register [/1]

### Register [POST /users]

+ Request (application/json)

        {
            "user":{
                "username": "john.smith",
                "firstName": "John",
                "lastName": "Smith",
                "password": "password1",
                "email": "john.smith@email.com"
            }
        }

+ Response 200 (application/json)

        {
            "result": "OK"
        }

### Register with external provider [POST /users/externalproviders]

+ Request (application/json)

        {
            "user":{
                "username": "juanito",
                "firstName": "Juanito",
                "lastName": "Rodríguez",
                "password": "password",
                "email": "pepe@pepe.com"
            },
            "externalId":"1234567890",
            "accessToken":"OAUTH_TOKEN",
            "externalProviderType":"FACEBOOK"
        }

+ Response 200 (application/json)

        {
            "result": "OK"
        }

### Activate account [GET /users/activate/{token}]

+ Parameters
    + token (string) - The activation token associated with the user profile.
    
+ Response 200 (application/json)

        {
            "result": "OK"
        }

## Login [/2]

### Login [POST /login]

+ Request (application/json)

        {
            "username":"john.smith", 
            "password":"password"
        }

+ Response 200 (application/json)

        {
            "user": {
                "id": 40,
                "guid": "8DThjgKFjJpJj",
                "username": "john.smith",
                "firstName": "John",
                "lastName": "Smith",
                "email": "john.smith@email.com",
                "followedByCurrentUser": false,
                "createdOn": "Sun, 27 Mar 2016 22:23:25 +0000"
            }
        }

### Login with external provider [POST /externalproviders/login]

+ Request (application/json)

        {
            "externalProvider":{
                "externalId":"1234567890",
                "accessToken":"OAUTH_TOKEN",
                "externalProviderType":"FACEBOOK"
            }
        }

+ Response 200 (application/json)

        {
            "user": {
                "id": 40,
                "guid": "8DThjgKFjJpJj",
                "username": "john.smith",
                "firstName": "John",
                "lastName": "Smith",
                "email": "john.smith@email.com",
                "followedByCurrentUser": false,
                "createdOn": "Sun, 27 Mar 2016 22:23:25 +0000"
            }
        }

### Logout [POST /logout]

+ Response 200 (application/json)

        {}

### Request password reset [POST /users/resetpassword]

+ Request (application/json)

        {
            "email":"jsmith@gmail.com"
        }

+ Response 200 (application/json)

        {
            "result": "OK"
        }

### Reset password [PUT /users/resetpassword/{token}]

+ Parameters
    + token (string) - The password reset token.

+ Request (application/json)

        {
            "password":"password"
        }

+ Response 200 (application/json)

        {
            "result": "OK"
        }

## Profile [/5]

### Get profile [GET /users/{id}]

🔒 __Requires authentication__

+ Parameters
    + id (number) - The ID of the user to get.

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "user": {
                "id": 40,
                "guid": "8DThjgKFjJpJj",
                "username": "john.smith",
                "firstName": "John",
                "lastName": "Smith",
                "email": "john.smith@email.com",
                "followedByCurrentUser": false,
                "createdOn": "Sun, 27 Mar 2016 22:23:25 +0000"
            }
        }

### Get full profile [GET /users/{id}/profile]

🔒 __Requires authentication__

+ Parameters
    + id (number) - The ID of the user to get.

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "user": {
                "id": 40,
                "guid": "8DThjgKFjJpJj",
                "username": "john.smith",
                "firstName": "John",
                "lastName": "Smith",
                "email": "john.smith@email.com",
                "followedByCurrentUser": false,
                "createdOn": "Sun, 27 Mar 2016 22:23:25 +0000",
                "followersCount": "123",
                "followingCount": "12",
                "streamablesCount": "54"
            }
        }

### Get profile by username [GET /users/username/{username}]

🔒 __Requires authentication__

+ Parameters
    + username (string) - The username of the user to get.

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "user": {
                "id": 40,
                "guid": "8DThjgKFjJpJj",
                "username": "john.smith",
                "firstName": "John",
                "lastName": "Smith",
                "email": "john.smith@email.com",
                "followedByCurrentUser": false,
                "createdOn": "Sun, 27 Mar 2016 22:23:25 +0000"
            }
        }

### Get full profile by username [GET /users/{username}/profile]

🔒 __Requires authentication__

+ Parameters
    + username (string) - The username of the user to get.

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "user": {
                "id": 40,
                "guid": "8DThjgKFjJpJj",
                "username": "john.smith",
                "firstName": "John",
                "lastName": "Smith",
                "email": "john.smith@email.com",
                "followedByCurrentUser": false,
                "createdOn": "Sun, 27 Mar 2016 22:23:25 +0000",
                "followersCount": "123",
                "followingCount": "12",
                "streamablesCount": "54"
            }
        }

## Followers [/6]

### Follow [POST /users/{id}/followers]

🔒 __Requires authentication__

+ Parameters
    + id (number) - The ID of the user to follow.

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "user": {
                "id": 40,
                "guid": "8DThjgKFjJpJj",
                "username": "john.smith",
                "firstName": "John",
                "lastName": "Smith",
                "email": "john.smith@email.com",
                "followedByCurrentUser": false,
                "createdOn": "Sun, 27 Mar 2016 22:23:25 +0000",
                "followersCount": "123",
                "followingCount": "12",
                "streamablesCount": "54"
            }
        }

### Unfollow [DELETE /users/{id}/followers]

🔒 __Requires authentication__

+ Parameters
    + id (number) - The ID of the user to unfollow.

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "user": {
                "id": 40,
                "guid": "8DThjgKFjJpJj",
                "username": "john.smith",
                "firstName": "John",
                "lastName": "Smith",
                "email": "john.smith@email.com",
                "followedByCurrentUser": false,
                "createdOn": "Sun, 27 Mar 2016 22:23:25 +0000",
                "followersCount": "123",
                "followingCount": "12",
                "streamablesCount": "54"
            }
        }

### Get followers [GET /users/{id}/followers]

🔒 __Requires authentication__

+ Parameters
    + id (number) - The ID of the user.

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "items": [
                {
                    "id": 40,
                    "guid": "8DThjgKFjJpJj",
                    "username": "john.smith",
                    "firstName": "John",
                    "lastName": "Smith",
                    "email": "john.smith@email.com",
                    "followedByCurrentUser": false,
                    "createdOn": "Sun, 27 Mar 2016 22:23:25 +0000"
                }
            ]
        }

### Get following [GET /users/{id}/following]

🔒 __Requires authentication__

+ Parameters
    + id (number) - The ID of the user.

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "items": [
                {
                    "id": 40,
                    "guid": "8DThjgKFjJpJj",
                    "username": "john.smith",
                    "firstName": "John",
                    "lastName": "Smith",
                    "email": "john.smith@email.com",
                    "followedByCurrentUser": false,
                    "createdOn": "Sun, 27 Mar 2016 22:23:25 +0000"
                }
            ]
        }

## Streamables [/7]

### Get user streamables [GET /users/{id}/streamables]

🔒 __Requires authentication__

+ Parameters
    + id (number) - The ID of the user.

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "items": [
                {
                    "id": 47,
                    "user": {
                        "id": 29,
                        "guid": "wYaGeNOHt8pyH",
                        "username": "georgi",
                        "firstName": "Georgi",
                        "lastName": "Christov",
                        "email": "georgi.christov89@gmail.com",
                        "followedByCurrentUser": false,
                        "createdOn": "Tue, 22 Mar 2016 16:36:48 +0000",
                        "avatar": {
                            "guid": "zf7e73KJvpR22",
                            "link": "http://graffitab-eu1.s3.amazonaws.com/assets/zf7e73KJvpR22",
                            "type": "IMAGE"
                        },
                        "cover": {
                            "guid": "XHhUF4tNpceT6",
                            "link": "http://graffitab-eu1.s3.amazonaws.com/assets/XHhUF4tNpceT6",
                            "type": "IMAGE"
                        }
                    },
                    "createdOn": "Sat, 26 Mar 2016 20:09:19 +0000",
                    "isPrivate": false,
                    "isFlagged": false,
                    "asset": {
                        "guid": "pehHj7p8yksWQ",
                        "link": "http://graffitab-eu1.s3.amazonaws.com/assets/pehHj7p8yksWQ",
                        "type": "IMAGE"
                    },
                    "latitude": 55.123,
                    "longitude": 3.123456,
                    "roll": 12.3,
                    "yaw": 13.4,
                    "pitch": 1.234,
                    "type": "GRAFFITI"
                }
            ]
        }

# Most active [/8]

### Get most active users [GET /users/mostactive]

🔒 __Requires authentication__

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "items": [
                {
                    "id": 40,
                    "guid": "8DThjgKFjJpJj",
                    "username": "john.smith",
                    "firstName": "John",
                    "lastName": "Smith",
                    "email": "john.smith@email.com",
                    "followedByCurrentUser": false,
                    "createdOn": "Sun, 27 Mar 2016 22:23:25 +0000"
                }
            ]
        }

# Likes [/9]

### Get user liked streamables [GET /users/{id}/liked]

🔒 __Requires authentication__

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "items": [
                {
                    "isRead": false,
                    "liker": {
                        "id": 30,
                        "guid": "P4aESkf6nLS17",
                        "username": "mike",
                        "firstName": "Mike",
                        "lastName": "Langmayr",
                        "email": "test@test.com",
                        "followedByCurrentUser": false,
                        "createdOn": "Tue, 22 Mar 2016 16:36:48 +0000"
                    },
                    "likedStreamable": {
                        "id": 5,
                        "user": {
                            "id": 29,
                            "guid": "wYaGeNOHt8pyH",
                            "username": "georgi",
                            "firstName": "Georgi",
                            "lastName": "Christov",
                            "email": "georgi.christov89@gmail.com",
                            "followedByCurrentUser": false,
                            "createdOn": "Tue, 22 Mar 2016 16:36:48 +0000",
                            "avatar": {
                                "guid": "zf7e73KJvpR22",
                                "link": "http://graffitab-eu1.s3.amazonaws.com/assets/zf7e73KJvpR22",
                                "type": "IMAGE"
                            },
                            "cover": {
                                "guid": "XHhUF4tNpceT6",
                                "link": "http://graffitab-eu1.s3.amazonaws.com/assets/XHhUF4tNpceT6",
                                "type": "IMAGE"
                            }
                        },
                        "createdOn": "Mon, 14 Mar 2016 13:38:57 +0000",
                        "isPrivate": false,
                        "isFlagged": false,
                        "asset": {
                            "guid": "gRRK8N0oeJOv0",
                            "link": "http://graffitab-eu1.s3.amazonaws.com/assets/gRRK8N0oeJOv0",
                            "type": "IMAGE"
                        },
                        "latitude": 55.123,
                        "longitude": 3.123456,
                        "roll": 12.3,
                        "yaw": 13.4,
                        "pitch": 1.234,
                        "likersCount": 0,
                        "commentsCount": 0,
                        "type": "GRAFFITI"
                    },
                    "date": "Sat, 26 Mar 2016 15:35:41 +0000",
                    "type": "LIKE"
                }
            ]
        }

# Search [/10]

### Search [GET /users/search?query={query}]

🔒 __Requires authentication__

+ Parameters
    + query (string) - The query to search for.

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "items": [
                {
                    "id": 40,
                    "guid": "8DThjgKFjJpJj",
                    "username": "john.smith",
                    "firstName": "John",
                    "lastName": "Smith",
                    "email": "john.smith@email.com",
                    "followedByCurrentUser": false,
                    "createdOn": "Sun, 27 Mar 2016 22:23:25 +0000"
                }
            ]
        }

# Group Me

## Profile [/4]

### Get me [GET /users/me]

🔒 __Requires authentication__

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "user": {
                "id": 40,
                "guid": "8DThjgKFjJpJj",
                "username": "john.smith",
                "firstName": "John",
                "lastName": "Smith",
                "email": "john.smith@email.com",
                "followedByCurrentUser": false,
                "createdOn": "Sun, 27 Mar 2016 22:23:25 +0000"
            }
        }

### Get full profile [GET /users/me/profile]

🔒 __Requires authentication__

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "user": {
                "id": 40,
                "guid": "8DThjgKFjJpJj",
                "username": "john.smith",
                "firstName": "John",
                "lastName": "Smith",
                "email": "john.smith@email.com",
                "followedByCurrentUser": false,
                "createdOn": "Sun, 27 Mar 2016 22:23:25 +0000",
                "followersCount": "123",
                "followingCount": "12",
                "streamablesCount": "54"
            }
        }

## Edit [/3]

### Change password [PUT /users/me/changepassword]

🔒 __Requires authentication__

+ Request (application/json)

        {
            "currentPassword": "currentPassword", 
            "newPassword": "newPassword"
        }

    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "result": "OK"
        }

### Edit profile [PUT /users/me]

🔒 __Requires authentication__

+ Request (application/json)

        {
            "user": {
                "firstName": "John",
                "lastName": "Smith",
                "email": "john.smith@test.com",
                "about": "This is John",
                "website": "www.google.com"
            }
        }

    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "user": {
                "id": 40,
                "guid": "8DThjgKFjJpJj",
                "username": "john.smith",
                "firstName": "John",
                "lastName": "Smith",
                "email": "john.smith@email.com",
                "followedByCurrentUser": false,
                "createdOn": "Sun, 27 Mar 2016 22:23:25 +0000"
            }
        }

### Edit avatar [POST /users/me/avatar]

🔒 __Requires authentication__

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "asset": {
                "guid": "g1h3nmn43",
                "type": "IMAGE",
                "link": "DOWNLOAD_LINK"
            }
        }

### Import avatar from external provider [PUT /users/me/social/{type}/avatar]

🔒 __Requires authentication__

+ Parameters
    + type (string) - The type of network.

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "asset": {
                "guid": "g1h3nmn43",
                "type": "IMAGE",
                "link": "DOWNLOAD_LINK"
            }
        }

### Delete avatar [DELETE /users/me/avatar]

🔒 __Requires authentication__

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "result": "OK"
        }

### Edit cover [POST /users/me/cover]

🔒 __Requires authentication__

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "asset": {
                "guid": "g1h3nmn43",
                "type": "IMAGE",
                "link": "DOWNLOAD_LINK"
            }
        }

### Delete cover [DELETE /users/me/cover]

🔒 __Requires authentication__

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "result": "OK"
        }

## Notifications [/11]

### Get notifications [GET /users/me/notifications]

🔒 __Requires authentication__

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "items": [
                {
                    "isRead": false,
                    "liker": {
                        "id": 30,
                        "guid": "P4aESkf6nLS17",
                        "username": "mike",
                        "firstName": "Mike",
                        "lastName": "Langmayr",
                        "email": "test@test.com",
                        "followedByCurrentUser": false,
                        "createdOn": "Tue, 22 Mar 2016 16:36:48 +0000"
                    },
                    "likedStreamable": {
                        "id": 5,
                        "user": {
                            "id": 29,
                            "guid": "wYaGeNOHt8pyH",
                            "username": "georgi",
                            "firstName": "Georgi",
                            "lastName": "Christov",
                            "email": "georgi.christov89@gmail.com",
                            "followedByCurrentUser": false,
                            "createdOn": "Tue, 22 Mar 2016 16:36:48 +0000",
                            "avatar": {
                                "guid": "zf7e73KJvpR22",
                                "link": "http://graffitab-eu1.s3.amazonaws.com/assets/zf7e73KJvpR22",
                                "type": "IMAGE"
                            },
                            "cover": {
                                "guid": "XHhUF4tNpceT6",
                                "link": "http://graffitab-eu1.s3.amazonaws.com/assets/XHhUF4tNpceT6",
                                "type": "IMAGE"
                            }
                        },
                        "createdOn": "Mon, 14 Mar 2016 13:38:57 +0000",
                        "isPrivate": false,
                        "isFlagged": false,
                        "asset": {
                            "guid": "gRRK8N0oeJOv0",
                            "link": "http://graffitab-eu1.s3.amazonaws.com/assets/gRRK8N0oeJOv0",
                            "type": "IMAGE"
                        },
                        "latitude": 55.123,
                        "longitude": 3.123456,
                        "roll": 12.3,
                        "yaw": 13.4,
                        "pitch": 1.234,
                        "likersCount": 0,
                        "commentsCount": 0,
                        "type": "GRAFFITI"
                    },
                    "date": "Sat, 26 Mar 2016 15:35:41 +0000",
                    "type": "LIKE"
                }
            ]
        }

### Get number of unread notifications [GET /users/me/notifications/unreadcount]

🔒 __Requires authentication__

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "count": "12"
        }

## Locations [/12]

### Create location [POST /users/me/locations]

🔒 __Requires authentication__

+ Request (application/json)

        {
            "location":{
                "address": "Flat 9, West End Court",
                "latitude": 55.43234,
                "longitude": 3.12345
            }
        }

    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "location": {
                "id": 4,
                "address": "Flat 9, West End Court",
                "latitude": 55.43234,
                "longitude": 3.12345,
                "createdOn": "Tue, 29 Mar 2016 21:09:31 +0000"
            }
        }

### Edit location [PUT /users/me/locations/{id}]

🔒 __Requires authentication__

+ Parameters
    + id (number) - The id of the location to update.

+ Request (application/json)

        {
            "location":{
                "address": "Flat 9, West End Court",
                "latitude": 55.43234,
                "longitude": 3.12345
            }
        }

    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "location": {
                "id": 4,
                "address": "Flat 9, West End Court",
                "latitude": 55.43234,
                "longitude": 3.12345,
                "createdOn": "Tue, 29 Mar 2016 21:09:31 +0000",
                "updatedOn": "Tue, 29 Mar 2016 21:09:31 +0000"
            }
        }

### Delete location [DELETE /users/me/locations/{id}]

🔒 __Requires authentication__

+ Parameters
    + id (number) - The id of the location to delete.

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "result": "OK"
        }

### Get locations [GET /users/me/locations]

🔒 __Requires authentication__

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "items": [
                {
                    "id": 4,
                    "address": "Flat 9, West End Court",
                    "latitude": 55.43234,
                    "longitude": 3.12345,
                    "createdOn": "Tue, 29 Mar 2016 21:09:31 +0000",
                    "updatedOn": "Tue, 29 Mar 2016 21:09:31 +0000"
                }
            ]
        }

## External providers [/13]

### Link external provider [POST /users/me/externalproviders]

🔒 __Requires authentication__

+ Request (application/json)

        {
            "externalProvider":{
                "externalId":"1234567890",
                "accessToken":"OAUTH_TOKEN",
                "externalProviderType":"FACEBOOK"
            }
        }

    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "result": "OK"
        }

### Unlink external provider [DELETE /users/me/externalproviders]

🔒 __Requires authentication__

+ Request (application/json)

        {
            "externalProviderType":"FACEBOOK"
        }

    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "result": "OK"
        }

## Devices [/14]

### Register device [POST /users/me/devices]

🔒 __Requires authentication__

+ Request (application/json)

        {
            "device":{
                "token":"DEVICE_TOKEN",
                "osType":"IOS"
            }
        }

    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "result": "OK"
        }

### Unregister device [DELETE /users/me/devices]

🔒 __Requires authentication__

+ Request (application/json)

        {
            "device":{
                "token":"DEVICE_TOKEN",
                "osType":"IOS"
            }
        }

    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "result": "OK"
        }

## Followers [/15]

### Get followers [GET /users/me/followers]

🔒 __Requires authentication__

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "items": [
                {
                    "id": 40,
                    "guid": "8DThjgKFjJpJj",
                    "username": "john.smith",
                    "firstName": "John",
                    "lastName": "Smith",
                    "email": "john.smith@email.com",
                    "followedByCurrentUser": false,
                    "createdOn": "Sun, 27 Mar 2016 22:23:25 +0000"
                }
            ]
        }

### Get followers activity [GET /users/me/followers/activity]

🔒 __Requires authentication__

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "items": [
                {
                    "user": {
                        "id": 29,
                        "guid": "wYaGeNOHt8pyH",
                        "username": "georgi",
                        "firstName": "Georgi",
                        "lastName": "Christov",
                        "email": "georgi.christov89@gmail.com",
                        "followedByCurrentUser": true,
                        "createdOn": "Tue, 22 Mar 2016 16:36:48 +0000",
                        "updatedOn": "Wed, 30 Mar 2016 21:34:14 +0000",
                        "avatar": {
                            "guid": "C7bo0yZbeUl07",
                            "link": "http://graffitab-eu1.s3.amazonaws.com/assets/C7bo0yZbeUl07",
                            "type": "IMAGE"
                        },
                        "cover": {
                            "guid": "XHhUF4tNpceT6",
                            "link": "http://graffitab-eu1.s3.amazonaws.com/assets/XHhUF4tNpceT6",
                            "type": "IMAGE"
                        }
                    },
                    "activities": [],
                    "date": "Tue, 29 Mar 2016 22:25:51 +0000",
                    "type": "COMMENT"
                }
            ]
        }

### Get following [GET /users/me/following]

🔒 __Requires authentication__

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "items": [
                {
                    "id": 40,
                    "guid": "8DThjgKFjJpJj",
                    "username": "john.smith",
                    "firstName": "John",
                    "lastName": "Smith",
                    "email": "john.smith@email.com",
                    "followedByCurrentUser": false,
                    "createdOn": "Sun, 27 Mar 2016 22:23:25 +0000"
                }
            ]
        }

## Streamables [/16]

### Create graffiti [POST /users/me/streamables/graffiti]

🔒 __Requires authentication__

+ Request (application/json)

        {
            "properties": {
                "latitude": 55.123, 
                "longitude": 3.123456, 
                "roll": 12.3, 
                "yaw": 13.4, 
                "pitch": 1.234
            }
        }

    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "streamable": {
                "id": 47,
                "user": {
                    "id": 29,
                    "guid": "wYaGeNOHt8pyH",
                    "username": "georgi",
                    "firstName": "Georgi",
                    "lastName": "Christov",
                    "email": "georgi.christov89@gmail.com",
                    "followedByCurrentUser": false,
                    "createdOn": "Tue, 22 Mar 2016 16:36:48 +0000",
                    "avatar": {
                        "guid": "zf7e73KJvpR22",
                        "link": "http://graffitab-eu1.s3.amazonaws.com/assets/zf7e73KJvpR22",
                        "type": "IMAGE"
                    },
                    "cover": {
                        "guid": "XHhUF4tNpceT6",
                        "link": "http://graffitab-eu1.s3.amazonaws.com/assets/XHhUF4tNpceT6",
                        "type": "IMAGE"
                    }
                },
                "createdOn": "Sat, 26 Mar 2016 20:09:19 +0000",
                "isPrivate": false,
                "isFlagged": false,
                "asset": {
                    "guid": "pehHj7p8yksWQ",
                    "link": "http://graffitab-eu1.s3.amazonaws.com/assets/pehHj7p8yksWQ",
                    "type": "IMAGE"
                },
                "latitude": 55.123,
                "longitude": 3.123456,
                "roll": 12.3,
                "yaw": 13.4,
                "pitch": 1.234,
                "type": "GRAFFITI"
            }
        }

### Edit graffiti [POST /users/me/streamables/graffiti/{id}]

🔒 __Requires authentication__

+ Parameters
    + id (number) - The id of the streamable to edit.

+ Request (application/json)

        {
            "properties": {
                "latitude": 55.123, 
                "longitude": 3.123456, 
                "roll": 12.3, 
                "yaw": 13.4, 
                "pitch": 1.234
            }
        }

    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "streamable": {
                "id": 47,
                "user": {
                    "id": 29,
                    "guid": "wYaGeNOHt8pyH",
                    "username": "georgi",
                    "firstName": "Georgi",
                    "lastName": "Christov",
                    "email": "georgi.christov89@gmail.com",
                    "followedByCurrentUser": false,
                    "createdOn": "Tue, 22 Mar 2016 16:36:48 +0000",
                    "avatar": {
                        "guid": "zf7e73KJvpR22",
                        "link": "http://graffitab-eu1.s3.amazonaws.com/assets/zf7e73KJvpR22",
                        "type": "IMAGE"
                    },
                    "cover": {
                        "guid": "XHhUF4tNpceT6",
                        "link": "http://graffitab-eu1.s3.amazonaws.com/assets/XHhUF4tNpceT6",
                        "type": "IMAGE"
                    }
                },
                "createdOn": "Sat, 26 Mar 2016 20:09:19 +0000",
                "isPrivate": false,
                "isFlagged": false,
                "asset": {
                    "guid": "pehHj7p8yksWQ",
                    "link": "http://graffitab-eu1.s3.amazonaws.com/assets/pehHj7p8yksWQ",
                    "type": "IMAGE"
                },
                "latitude": 55.123,
                "longitude": 3.123456,
                "roll": 12.3,
                "yaw": 13.4,
                "pitch": 1.234,
                "type": "GRAFFITI"
            }
        }

### Delete streamable [DELETE /users/me/streamables/{id}]

🔒 __Requires authentication__

+ Parameters
    + id (number) - The id of the streamable to delete.

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "result": "OK"
        }

### Get streamables [GET /users/me/streamables]

🔒 __Requires authentication__

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "items": [
                {
                    "id": 47,
                    "user": {
                        "id": 29,
                        "guid": "wYaGeNOHt8pyH",
                        "username": "georgi",
                        "firstName": "Georgi",
                        "lastName": "Christov",
                        "email": "georgi.christov89@gmail.com",
                        "followedByCurrentUser": false,
                        "createdOn": "Tue, 22 Mar 2016 16:36:48 +0000",
                        "avatar": {
                            "guid": "zf7e73KJvpR22",
                            "link": "http://graffitab-eu1.s3.amazonaws.com/assets/zf7e73KJvpR22",
                            "type": "IMAGE"
                        },
                        "cover": {
                            "guid": "XHhUF4tNpceT6",
                            "link": "http://graffitab-eu1.s3.amazonaws.com/assets/XHhUF4tNpceT6",
                            "type": "IMAGE"
                        }
                    },
                    "createdOn": "Sat, 26 Mar 2016 20:09:19 +0000",
                    "isPrivate": false,
                    "isFlagged": false,
                    "asset": {
                        "guid": "pehHj7p8yksWQ",
                        "link": "http://graffitab-eu1.s3.amazonaws.com/assets/pehHj7p8yksWQ",
                        "type": "IMAGE"
                    },
                    "latitude": 55.123,
                    "longitude": 3.123456,
                    "roll": 12.3,
                    "yaw": 13.4,
                    "pitch": 1.234,
                    "type": "GRAFFITI"
                }
            ]
        }

## Private streamables [/17]

### Mark streamable as private [PUT /users/me/streamables/{id}/private]

🔒 __Requires authentication__

+ Parameters
    + id (number) - The id of the streamable.

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "streamable": {
                "id": 47,
                "user": {
                    "id": 29,
                    "guid": "wYaGeNOHt8pyH",
                    "username": "georgi",
                    "firstName": "Georgi",
                    "lastName": "Christov",
                    "email": "georgi.christov89@gmail.com",
                    "followedByCurrentUser": false,
                    "createdOn": "Tue, 22 Mar 2016 16:36:48 +0000",
                    "avatar": {
                        "guid": "zf7e73KJvpR22",
                        "link": "http://graffitab-eu1.s3.amazonaws.com/assets/zf7e73KJvpR22",
                        "type": "IMAGE"
                    },
                    "cover": {
                        "guid": "XHhUF4tNpceT6",
                        "link": "http://graffitab-eu1.s3.amazonaws.com/assets/XHhUF4tNpceT6",
                        "type": "IMAGE"
                    }
                },
                "createdOn": "Sat, 26 Mar 2016 20:09:19 +0000",
                "isPrivate": true,
                "isFlagged": false,
                "asset": {
                    "guid": "pehHj7p8yksWQ",
                    "link": "http://graffitab-eu1.s3.amazonaws.com/assets/pehHj7p8yksWQ",
                    "type": "IMAGE"
                },
                "latitude": 55.123,
                "longitude": 3.123456,
                "roll": 12.3,
                "yaw": 13.4,
                "pitch": 1.234,
                "type": "GRAFFITI"
            }
        }

### Mark streamable as public [DELETE /users/me/streamables/{id}/private]

🔒 __Requires authentication__

+ Parameters
    + id (number) - The id of the streamable.

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "streamable": {
                "id": 47,
                "user": {
                    "id": 29,
                    "guid": "wYaGeNOHt8pyH",
                    "username": "georgi",
                    "firstName": "Georgi",
                    "lastName": "Christov",
                    "email": "georgi.christov89@gmail.com",
                    "followedByCurrentUser": false,
                    "createdOn": "Tue, 22 Mar 2016 16:36:48 +0000",
                    "avatar": {
                        "guid": "zf7e73KJvpR22",
                        "link": "http://graffitab-eu1.s3.amazonaws.com/assets/zf7e73KJvpR22",
                        "type": "IMAGE"
                    },
                    "cover": {
                        "guid": "XHhUF4tNpceT6",
                        "link": "http://graffitab-eu1.s3.amazonaws.com/assets/XHhUF4tNpceT6",
                        "type": "IMAGE"
                    }
                },
                "createdOn": "Sat, 26 Mar 2016 20:09:19 +0000",
                "isPrivate": false,
                "isFlagged": false,
                "asset": {
                    "guid": "pehHj7p8yksWQ",
                    "link": "http://graffitab-eu1.s3.amazonaws.com/assets/pehHj7p8yksWQ",
                    "type": "IMAGE"
                },
                "latitude": 55.123,
                "longitude": 3.123456,
                "roll": 12.3,
                "yaw": 13.4,
                "pitch": 1.234,
                "type": "GRAFFITI"
            }
        }

### Get private streamables [GET /users/me/streamables/private]

🔒 __Requires authentication__

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "items": [
                {
                    "id": 47,
                    "user": {
                        "id": 29,
                        "guid": "wYaGeNOHt8pyH",
                        "username": "georgi",
                        "firstName": "Georgi",
                        "lastName": "Christov",
                        "email": "georgi.christov89@gmail.com",
                        "followedByCurrentUser": false,
                        "createdOn": "Tue, 22 Mar 2016 16:36:48 +0000",
                        "avatar": {
                            "guid": "zf7e73KJvpR22",
                            "link": "http://graffitab-eu1.s3.amazonaws.com/assets/zf7e73KJvpR22",
                            "type": "IMAGE"
                        },
                        "cover": {
                            "guid": "XHhUF4tNpceT6",
                            "link": "http://graffitab-eu1.s3.amazonaws.com/assets/XHhUF4tNpceT6",
                            "type": "IMAGE"
                        }
                    },
                    "createdOn": "Sat, 26 Mar 2016 20:09:19 +0000",
                    "isPrivate": false,
                    "isFlagged": false,
                    "asset": {
                        "guid": "pehHj7p8yksWQ",
                        "link": "http://graffitab-eu1.s3.amazonaws.com/assets/pehHj7p8yksWQ",
                        "type": "IMAGE"
                    },
                    "latitude": 55.123,
                    "longitude": 3.123456,
                    "roll": 12.3,
                    "yaw": 13.4,
                    "pitch": 1.234,
                    "type": "GRAFFITI"
                }
            ]
        }

## Feed [/18]

### Get feed [GET /users/me/feed]

🔒 __Requires authentication__

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "items": [
                {
                    "id": 47,
                    "user": {
                        "id": 29,
                        "guid": "wYaGeNOHt8pyH",
                        "username": "georgi",
                        "firstName": "Georgi",
                        "lastName": "Christov",
                        "email": "georgi.christov89@gmail.com",
                        "followedByCurrentUser": false,
                        "createdOn": "Tue, 22 Mar 2016 16:36:48 +0000",
                        "avatar": {
                            "guid": "zf7e73KJvpR22",
                            "link": "http://graffitab-eu1.s3.amazonaws.com/assets/zf7e73KJvpR22",
                            "type": "IMAGE"
                        },
                        "cover": {
                            "guid": "XHhUF4tNpceT6",
                            "link": "http://graffitab-eu1.s3.amazonaws.com/assets/XHhUF4tNpceT6",
                            "type": "IMAGE"
                        }
                    },
                    "createdOn": "Sat, 26 Mar 2016 20:09:19 +0000",
                    "isPrivate": false,
                    "isFlagged": false,
                    "asset": {
                        "guid": "pehHj7p8yksWQ",
                        "link": "http://graffitab-eu1.s3.amazonaws.com/assets/pehHj7p8yksWQ",
                        "type": "IMAGE"
                    },
                    "latitude": 55.123,
                    "longitude": 3.123456,
                    "roll": 12.3,
                    "yaw": 13.4,
                    "pitch": 1.234,
                    "type": "GRAFFITI"
                }
            ]
        }

## Likes [/19]

### Get liked streamables [GET /users/me/liked]

🔒 __Requires authentication__

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "items": [
                {
                    "id": 47,
                    "user": {
                        "id": 29,
                        "guid": "wYaGeNOHt8pyH",
                        "username": "georgi",
                        "firstName": "Georgi",
                        "lastName": "Christov",
                        "email": "georgi.christov89@gmail.com",
                        "followedByCurrentUser": false,
                        "createdOn": "Tue, 22 Mar 2016 16:36:48 +0000",
                        "avatar": {
                            "guid": "zf7e73KJvpR22",
                            "link": "http://graffitab-eu1.s3.amazonaws.com/assets/zf7e73KJvpR22",
                            "type": "IMAGE"
                        },
                        "cover": {
                            "guid": "XHhUF4tNpceT6",
                            "link": "http://graffitab-eu1.s3.amazonaws.com/assets/XHhUF4tNpceT6",
                            "type": "IMAGE"
                        }
                    },
                    "createdOn": "Sat, 26 Mar 2016 20:09:19 +0000",
                    "isPrivate": false,
                    "isFlagged": false,
                    "asset": {
                        "guid": "pehHj7p8yksWQ",
                        "link": "http://graffitab-eu1.s3.amazonaws.com/assets/pehHj7p8yksWQ",
                        "type": "IMAGE"
                    },
                    "latitude": 55.123,
                    "longitude": 3.123456,
                    "roll": 12.3,
                    "yaw": 13.4,
                    "pitch": 1.234,
                    "type": "GRAFFITI"
                }
            ]
        }

## Social [/20]

### Get social friends [GET /users/me/social/friends]

🔒 __Requires authentication__

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "items": [
                {
                    "users": [
                        {
                            "id": 33,
                            "guid": "MySXGYns4qCBH",
                            "username": "david",
                            "firstName": "David",
                            "lastName": "Fernandez",
                            "email": "test1@test.com",
                            "followedByCurrentUser": false,
                            "createdOn": "Tue, 22 Mar 2016 16:36:48 +0000"
                        }
                    ],
                    "type": "FACEBOOK",
                    "resultsCount": 1,
                    "offset": 0,
                    "limit": 20
                }
            ],
            "resultsCount": 1
        }

### Get social friends for network [GET /users/me/social/{type}/friends]

🔒 __Requires authentication__

+ Parameters
    + type (string) - The type of network.

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "users": [
                {
                    "id": 33,
                    "guid": "MySXGYns4qCBH",
                    "username": "david",
                    "firstName": "David",
                    "lastName": "Fernandez",
                    "email": "test1@test.com",
                    "followedByCurrentUser": false,
                    "createdOn": "Tue, 22 Mar 2016 16:36:48 +0000"
                }
            ],
            "type": "FACEBOOK",
            "resultsCount": 1,
            "offset": 0,
            "limit": 20
        }

# Group Streamables

### Get streamable [POST /streamables/{id}]

🔒 __Requires authentication__

+ Parameters
    + id (number) - The ID of the streamable.

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "streamable": {
                "id": 47,
                "user": {
                    "id": 29,
                    "guid": "wYaGeNOHt8pyH",
                    "username": "georgi",
                    "firstName": "Georgi",
                    "lastName": "Christov",
                    "email": "georgi.christov89@gmail.com",
                    "followedByCurrentUser": false,
                    "createdOn": "Tue, 22 Mar 2016 16:36:48 +0000",
                    "avatar": {
                        "guid": "zf7e73KJvpR22",
                        "link": "http://graffitab-eu1.s3.amazonaws.com/assets/zf7e73KJvpR22",
                        "type": "IMAGE"
                    },
                    "cover": {
                        "guid": "XHhUF4tNpceT6",
                        "link": "http://graffitab-eu1.s3.amazonaws.com/assets/XHhUF4tNpceT6",
                        "type": "IMAGE"
                    }
                },
                "createdOn": "Sat, 26 Mar 2016 20:09:19 +0000",
                "isPrivate": false,
                "isFlagged": false,
                "asset": {
                    "guid": "pehHj7p8yksWQ",
                    "link": "http://graffitab-eu1.s3.amazonaws.com/assets/pehHj7p8yksWQ",
                    "type": "IMAGE"
                },
                "latitude": 55.123,
                "longitude": 3.123456,
                "roll": 12.3,
                "yaw": 13.4,
                "pitch": 1.234,
                "type": "GRAFFITI"
            }
        }

## Likes [/21]

### Like streamable [POST /streamables/{id}/likes]

🔒 __Requires authentication__

+ Parameters
    + id (number) - The ID of the streamable to like.

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "streamable": {
                "id": 47,
                "user": {
                    "id": 29,
                    "guid": "wYaGeNOHt8pyH",
                    "username": "georgi",
                    "firstName": "Georgi",
                    "lastName": "Christov",
                    "email": "georgi.christov89@gmail.com",
                    "followedByCurrentUser": false,
                    "createdOn": "Tue, 22 Mar 2016 16:36:48 +0000",
                    "avatar": {
                        "guid": "zf7e73KJvpR22",
                        "link": "http://graffitab-eu1.s3.amazonaws.com/assets/zf7e73KJvpR22",
                        "type": "IMAGE"
                    },
                    "cover": {
                        "guid": "XHhUF4tNpceT6",
                        "link": "http://graffitab-eu1.s3.amazonaws.com/assets/XHhUF4tNpceT6",
                        "type": "IMAGE"
                    }
                },
                "createdOn": "Sat, 26 Mar 2016 20:09:19 +0000",
                "isPrivate": false,
                "isFlagged": false,
                "asset": {
                    "guid": "pehHj7p8yksWQ",
                    "link": "http://graffitab-eu1.s3.amazonaws.com/assets/pehHj7p8yksWQ",
                    "type": "IMAGE"
                },
                "latitude": 55.123,
                "longitude": 3.123456,
                "roll": 12.3,
                "yaw": 13.4,
                "pitch": 1.234,
                "type": "GRAFFITI"
            }
        }

### Unlike streamable [DELETE /streamables/{streamable_id}/likes]

🔒 __Requires authentication__

+ Parameters
    + streamable_id (number) - The ID of the streamable to unlike.

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "streamable": {
                "id": 47,
                "user": {
                    "id": 29,
                    "guid": "wYaGeNOHt8pyH",
                    "username": "georgi",
                    "firstName": "Georgi",
                    "lastName": "Christov",
                    "email": "georgi.christov89@gmail.com",
                    "followedByCurrentUser": false,
                    "createdOn": "Tue, 22 Mar 2016 16:36:48 +0000",
                    "avatar": {
                        "guid": "zf7e73KJvpR22",
                        "link": "http://graffitab-eu1.s3.amazonaws.com/assets/zf7e73KJvpR22",
                        "type": "IMAGE"
                    },
                    "cover": {
                        "guid": "XHhUF4tNpceT6",
                        "link": "http://graffitab-eu1.s3.amazonaws.com/assets/XHhUF4tNpceT6",
                        "type": "IMAGE"
                    }
                },
                "createdOn": "Sat, 26 Mar 2016 20:09:19 +0000",
                "isPrivate": false,
                "isFlagged": false,
                "asset": {
                    "guid": "pehHj7p8yksWQ",
                    "link": "http://graffitab-eu1.s3.amazonaws.com/assets/pehHj7p8yksWQ",
                    "type": "IMAGE"
                },
                "latitude": 55.123,
                "longitude": 3.123456
                "roll": 12.3,
                "yaw": 13.4,
                "pitch": 1.234,
                "type": "GRAFFITI"
            }
        }

### Get likers [GET /streamables/{id}/likes]

🔒 __Requires authentication__

+ Parameters
    + id (number) - The ID of the streamable.

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "items": [
                {
                    "id": 40,
                    "guid": "8DThjgKFjJpJj",
                    "username": "john.smith",
                    "firstName": "John",
                    "lastName": "Smith",
                    "email": "john.smith@email.com",
                    "followedByCurrentUser": false,
                    "createdOn": "Sun, 27 Mar 2016 22:23:25 +0000"
                }
            ]
        }

## Comments [/22]

### Post comment [POST /streamables/{id}/comments]

🔒 __Requires authentication__

+ Parameters
    + id (number) - The ID of the streamable.

+ Request (application/json)

        {
            "comment": {
                "text": "This is a comment."
            }
        }

    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "comment": {
                "id": 63,
                "user": {
                    "id": 29,
                    "guid": "wYaGeNOHt8pyH",
                    "username": "georgi",
                    "firstName": "Georgi",
                    "lastName": "Christov",
                    "email": "georgi.christov89@gmail.com",
                    "followedByCurrentUser": false,
                    "createdOn": "Tue, 22 Mar 2016 16:36:48 +0000",
                    "avatar": {
                        "guid": "zf7e73KJvpR22",
                        "link": "http://graffitab-eu1.s3.amazonaws.com/assets/zf7e73KJvpR22",
                        "type": "IMAGE"
                    },
                    "cover": {
                        "guid": "XHhUF4tNpceT6",
                        "link": "http://graffitab-eu1.s3.amazonaws.com/assets/XHhUF4tNpceT6",
                        "type": "IMAGE"
                    }
                },
                "text": "This is a comment.",
                "createdOn": "Tue, 29 Mar 2016 22:25:51 +0000"
            }
        }

### Delete comment [DELETE /streamables/{streamable_id}/comments/{comment_id}]

🔒 __Requires authentication__

+ Parameters
    + streamable_id (number) - The ID of the streamable.
    + comment_id (number) - The ID of the comment to delete.

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "result": "OK"
        }

### Edit comment [PUT /streamables/{streamable_id}/comments/{comment_id}]

🔒 __Requires authentication__

+ Parameters
    + streamable_id (number) - The ID of the streamable.
    + comment_id (number) - The ID of the comment to edit.

+ Request (application/json)

        {
            "comment": {
                "text": "This is a comment."
            }
        }

    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "comment": {
                "id": 63,
                "user": {
                    "id": 29,
                    "guid": "wYaGeNOHt8pyH",
                    "username": "georgi",
                    "firstName": "Georgi",
                    "lastName": "Christov",
                    "email": "georgi.christov89@gmail.com",
                    "followedByCurrentUser": false,
                    "createdOn": "Tue, 22 Mar 2016 16:36:48 +0000",
                    "avatar": {
                        "guid": "zf7e73KJvpR22",
                        "link": "http://graffitab-eu1.s3.amazonaws.com/assets/zf7e73KJvpR22",
                        "type": "IMAGE"
                    },
                    "cover": {
                        "guid": "XHhUF4tNpceT6",
                        "link": "http://graffitab-eu1.s3.amazonaws.com/assets/XHhUF4tNpceT6",
                        "type": "IMAGE"
                    }
                },
                "text": "This is a comment.",
                "createdOn": "Tue, 29 Mar 2016 22:25:51 +0000"
                "updatedOn": "Tue, 29 Mar 2016 22:25:51 +0000"
            }
        }

### Get comments [GET /streamables/{id}/comments]

🔒 __Requires authentication__

+ Parameters
    + id (number) - The ID of the streamable.

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "items": [
                {
                    "comment": {
                        "id": 63,
                        "user": {
                            "id": 29,
                            "guid": "wYaGeNOHt8pyH",
                            "username": "georgi",
                            "firstName": "Georgi",
                            "lastName": "Christov",
                            "email": "georgi.christov89@gmail.com",
                            "followedByCurrentUser": false,
                            "createdOn": "Tue, 22 Mar 2016 16:36:48 +0000",
                            "avatar": {
                                "guid": "zf7e73KJvpR22",
                                "link": "http://graffitab-eu1.s3.amazonaws.com/assets/zf7e73KJvpR22",
                                "type": "IMAGE"
                            },
                            "cover": {
                                "guid": "XHhUF4tNpceT6",
                                "link": "http://graffitab-eu1.s3.amazonaws.com/assets/XHhUF4tNpceT6",
                                "type": "IMAGE"
                            }
                        },
                        "text": "This is a comment.",
                        "createdOn": "Tue, 29 Mar 2016 22:25:51 +0000"
                        "updatedOn": "Tue, 29 Mar 2016 22:25:51 +0000"
                    }
                }
            ]
        }

## Newest [/23]

### Get newest streamables [GET /streamables/newest]

🔒 __Requires authentication__

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "items": [
                {
                    "id": 47,
                    "user": {
                        "id": 29,
                        "guid": "wYaGeNOHt8pyH",
                        "username": "georgi",
                        "firstName": "Georgi",
                        "lastName": "Christov",
                        "email": "georgi.christov89@gmail.com",
                        "followedByCurrentUser": false,
                        "createdOn": "Tue, 22 Mar 2016 16:36:48 +0000",
                        "avatar": {
                            "guid": "zf7e73KJvpR22",
                            "link": "http://graffitab-eu1.s3.amazonaws.com/assets/zf7e73KJvpR22",
                            "type": "IMAGE"
                        },
                        "cover": {
                            "guid": "XHhUF4tNpceT6",
                            "link": "http://graffitab-eu1.s3.amazonaws.com/assets/XHhUF4tNpceT6",
                            "type": "IMAGE"
                        }
                    },
                    "createdOn": "Sat, 26 Mar 2016 20:09:19 +0000",
                    "isPrivate": false,
                    "isFlagged": false,
                    "asset": {
                        "guid": "pehHj7p8yksWQ",
                        "link": "http://graffitab-eu1.s3.amazonaws.com/assets/pehHj7p8yksWQ",
                        "type": "IMAGE"
                    },
                    "latitude": 55.123,
                    "longitude": 3.123456,
                    "roll": 12.3,
                    "yaw": 13.4,
                    "pitch": 1.234,
                    "type": "GRAFFITI"
                }
            ]
        }

## Popular [/24]

### Get popular streamables [GET /streamables/popular]

🔒 __Requires authentication__

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "items": [
                {
                    "id": 47,
                    "user": {
                        "id": 29,
                        "guid": "wYaGeNOHt8pyH",
                        "username": "georgi",
                        "firstName": "Georgi",
                        "lastName": "Christov",
                        "email": "georgi.christov89@gmail.com",
                        "followedByCurrentUser": false,
                        "createdOn": "Tue, 22 Mar 2016 16:36:48 +0000",
                        "avatar": {
                            "guid": "zf7e73KJvpR22",
                            "link": "http://graffitab-eu1.s3.amazonaws.com/assets/zf7e73KJvpR22",
                            "type": "IMAGE"
                        },
                        "cover": {
                            "guid": "XHhUF4tNpceT6",
                            "link": "http://graffitab-eu1.s3.amazonaws.com/assets/XHhUF4tNpceT6",
                            "type": "IMAGE"
                        }
                    },
                    "createdOn": "Sat, 26 Mar 2016 20:09:19 +0000",
                    "isPrivate": false,
                    "isFlagged": false,
                    "asset": {
                        "guid": "pehHj7p8yksWQ",
                        "link": "http://graffitab-eu1.s3.amazonaws.com/assets/pehHj7p8yksWQ",
                        "type": "IMAGE"
                    },
                    "latitude": 55.123,
                    "longitude": 3.123456,
                    "roll": 12.3,
                    "yaw": 13.4,
                    "pitch": 1.234,
                    "type": "GRAFFITI"
                }
            ]
        }

## Flag [/25]

### Flag streamable [PUT /streamables/{id}/flag]

🔒 __Requires authentication__

+ Parameters
    + id (number) - The ID of the streamable to flag.

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "streamable": {
                "id": 47,
                "user": {
                    "id": 29,
                    "guid": "wYaGeNOHt8pyH",
                    "username": "georgi",
                    "firstName": "Georgi",
                    "lastName": "Christov",
                    "email": "georgi.christov89@gmail.com",
                    "followedByCurrentUser": false,
                    "createdOn": "Tue, 22 Mar 2016 16:36:48 +0000",
                    "avatar": {
                        "guid": "zf7e73KJvpR22",
                        "link": "http://graffitab-eu1.s3.amazonaws.com/assets/zf7e73KJvpR22",
                        "type": "IMAGE"
                    },
                    "cover": {
                        "guid": "XHhUF4tNpceT6",
                        "link": "http://graffitab-eu1.s3.amazonaws.com/assets/XHhUF4tNpceT6",
                        "type": "IMAGE"
                    }
                },
                "createdOn": "Sat, 26 Mar 2016 20:09:19 +0000",
                "isPrivate": false,
                "isFlagged": true,
                "asset": {
                    "guid": "pehHj7p8yksWQ",
                    "link": "http://graffitab-eu1.s3.amazonaws.com/assets/pehHj7p8yksWQ",
                    "type": "IMAGE"
                },
                "latitude": 55.123,
                "longitude": 3.123456,
                "roll": 12.3,
                "yaw": 13.4,
                "pitch": 1.234,
                "type": "GRAFFITI"
            }
        }

## Search [/26]

### Search location [GET /streamables/search/location?neLatitude={neLatitude}&neLongitude={neLongitude}&swLatitude={swLatitude}&swLongitude={swLongitude}]

🔒 __Requires authentication__

+ Parameters
    + neLatitude (number) - Top right corner of the boundary GPS rectangle.
    + neLongitude (number) - Top right corner of the boundary GPS rectangle.
    + swLatitude (number) - Bottom right corner of the boundary GPS rectangle.
    + swLongitude (number) - Bottom right corner of the boundary GPS rectangle.

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "items": [
                {
                    "id": 47,
                    "user": {
                        "id": 29,
                        "guid": "wYaGeNOHt8pyH",
                        "username": "georgi",
                        "firstName": "Georgi",
                        "lastName": "Christov",
                        "email": "georgi.christov89@gmail.com",
                        "followedByCurrentUser": false,
                        "createdOn": "Tue, 22 Mar 2016 16:36:48 +0000",
                        "avatar": {
                            "guid": "zf7e73KJvpR22",
                            "link": "http://graffitab-eu1.s3.amazonaws.com/assets/zf7e73KJvpR22",
                            "type": "IMAGE"
                        },
                        "cover": {
                            "guid": "XHhUF4tNpceT6",
                            "link": "http://graffitab-eu1.s3.amazonaws.com/assets/XHhUF4tNpceT6",
                            "type": "IMAGE"
                        }
                    },
                    "createdOn": "Sat, 26 Mar 2016 20:09:19 +0000",
                    "isPrivate": false,
                    "isFlagged": false,
                    "asset": {
                        "guid": "pehHj7p8yksWQ",
                        "link": "http://graffitab-eu1.s3.amazonaws.com/assets/pehHj7p8yksWQ",
                        "type": "IMAGE"
                    },
                    "latitude": 55.123,
                    "longitude": 3.123456,
                    "roll": 12.3,
                    "yaw": 13.4,
                    "pitch": 1.234,
                    "type": "GRAFFITI"
                }
            ]
        }

### Search hashtag [GET /streamables/search/hashtag?query={query}]

🔒 __Requires authentication__

+ Parameters
    + query (string) - The hash tag to search for.

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "items": [
                {
                    "id": 47,
                    "user": {
                        "id": 29,
                        "guid": "wYaGeNOHt8pyH",
                        "username": "georgi",
                        "firstName": "Georgi",
                        "lastName": "Christov",
                        "email": "georgi.christov89@gmail.com",
                        "followedByCurrentUser": false,
                        "createdOn": "Tue, 22 Mar 2016 16:36:48 +0000",
                        "avatar": {
                            "guid": "zf7e73KJvpR22",
                            "link": "http://graffitab-eu1.s3.amazonaws.com/assets/zf7e73KJvpR22",
                            "type": "IMAGE"
                        },
                        "cover": {
                            "guid": "XHhUF4tNpceT6",
                            "link": "http://graffitab-eu1.s3.amazonaws.com/assets/XHhUF4tNpceT6",
                            "type": "IMAGE"
                        }
                    },
                    "createdOn": "Sat, 26 Mar 2016 20:09:19 +0000",
                    "isPrivate": false,
                    "isFlagged": false,
                    "asset": {
                        "guid": "pehHj7p8yksWQ",
                        "link": "http://graffitab-eu1.s3.amazonaws.com/assets/pehHj7p8yksWQ",
                        "type": "IMAGE"
                    },
                    "latitude": 55.123,
                    "longitude": 3.123456,
                    "roll": 12.3,
                    "yaw": 13.4,
                    "pitch": 1.234,
                    "type": "GRAFFITI"
                }
            ]
        }

### Search hashtags [GET /streamables/search/hashtags?query={query}]

🔒 __Requires authentication__

+ Parameters
    + query (string) - The hash tag to search for.

+ Request (application/json)
    + Headers
    
            Authorization:Basic [access_token]

+ Response 200 (application/json)

        {
            "items": [
                "hashtag1",
                "hashtag2"
            ],
            "resultsCount": 1,
            "offset": 0,
            "limit": 10
        }

# Group Assets

## State [/29]

### Get Asset state [GET /assets/{guid}/progress]

+ Response 200 (application/json)

        "avatar": {
            "guid": "zf7e73KJvpR22",
            "link": "http://graffitab-eu1.s3.amazonaws.com/assets/zf7e73KJvpR22",
            "type": "IMAGE"
        }

# Group Feedback

## General [/27]

### Send feedback [POST /feedback]

+ Request (application/json)

        {
            "feedback": {
                "name": "Georgi",
                "email": "georgi.christov89@gmail.com",
                "text": "This is some feedback."
            }
        }

+ Response 200 (application/json)

        {
            "result": "OK"
        }